name: WEB-Product

on:
  push:
    branches: [latest]
    paths: [src/**]
    tags: [ v* ]
  pull_request:
    types: [closed]
    paths: [src/**]

env:
  # Use docker.io for Docker Hub (Default) / Use ghcr.io for GitHub Container Registry
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    # Ensures that docker action will not run on pull requests in draft state
    if: github.event.pull_request.merged == true && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Make ENVFILE
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{ secrets.PROD_PORT1 }}
          envkey_REACT_APP_HOST: ${{ secrets.PROD_API }}
          envkey_REACT_APP_DEV: ${{ secrets.PROD_DEV }}
          file_name: .env
          directory: ./src/
      # - 
      #   name: Generate Nginx configuration file
      #   run: |
      #     cat <<EOT >> ./nginx.conf
      #     events {
      #         worker_connections 1024;
      #     }

      #     http {
      #         server {
      #             listen ${{ secrets.PROD_PORT1 }};
      #             server_name sci.cugrader.com www.sci.cugrader.com;

      #             # Redirect HTTP to HTTPS
      #             location / {
      #                 return 301 https://\$host\$request_uri;
      #             }
      #         }

      #         server {
      #             listen ${{ secrets.PROD_PORT2 }} ssl;
      #             server_name sci.cugrader.com www.sci.cugrader.com;

      #             ssl_certificate ${{ secrets.PROD_CERT }};
      #             ssl_certificate_key ${{ secrets.PROD_CERTKEY }};

      #             ssl_protocols TLSv1.2 TLSv1.3;
      #             ssl_prefer_server_ciphers on;

      #             location / {
      #                 root /usr/share/nginx/html;
      #                 index index.html;
      #                 try_files \$uri \$uri/ /index.html;
      #             }

      #             location /api {
      #                 proxy_pass ${{ secrets.PROD_API }};
      #                 proxy_set_header Host \$host;
      #                 proxy_set_header X-Real-IP \$remote_addr;
      #                 proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      #                 proxy_set_header X-Forwarded-Proto \$scheme;
      #             }
      #         }
      #     }
      #     EOT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # Username and Password for DOCKER HUB
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Username and Password for GITHUB CONTAINER REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: "."
          push: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max